name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "5 20 * * 2"

env:
  AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
  AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
  AIRTABLE_TABLE: ${{ secrets.AIRTABLE_TABLE }}
  AIRTABLE_VIEW: ${{ secrets.AIRTABLE_VIEW }}
  REPORT_ERROR_PATH: ${{ secrets.REPORT_ERROR_PATH }}
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "17.x"

      - run: npm ci --prefer-offline --no-audit --no-optional --legacy-peer-deps

      - run: npm run build

      - name: Setup GitHub pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4
