name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
  AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}
  AIRTABLE_TABLE: ${{ secrets.AIRTABLE_TABLE }}
  AIRTABLE_VIEW: ${{ secrets.AIRTABLE_VIEW }}
  REPORT_ERROR_PATH: ${{ secrets.REPORT_ERROR_PATH }}
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - run: npm ci --prefer-offline --no-audit --no-optional

      - run: npm run build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
